In [1]:
import numpy as np

In [6]:
arr = np.array([[[1, 2, 3, 4, 5]]])
print(arr)

[[[1 2 3 4 5]]]


In [7]:
print(arr.ndim)

3


In [8]:
print(arr.shape)

(1, 1, 5)


In [15]:
range = np.arange(1,30,3)
print(range)
# what is thiss range 


[ 1  4  7 10 13 16 19 22 25 28]


In [ ]:
arr= np.linspace(0,1,5)
print(arr)
# it divides the range into 5 equal parts and gives us the values in those parts.

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
arr = np.logspace(2,3,5)
print(arr)
# it divides the range into 5 equal parts and gives us the values in those parts but in log scale.

[ 100.          177.827941    316.22776602  562.34132519 1000.        ]


In [20]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [25]:
arr = np.ones([4,5])
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
arr = np.full([4,5],6)
print(arr)

[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [27]:
arr = np.random.rand(1,3)
print(arr)

[[0.53047881 0.84811951 0.75276359]]


In [30]:
arr = np.random.randn(2,3)
print(arr)

[[-1.79155599 -1.16207008 -0.54732141]
 [ 0.32319185 -1.09703258 -0.14005618]]


In [31]:
arr = np.random.randchar(5,10)
print(arr)

AttributeError: module 'numpy.random' has no attribute 'randchar'